---

- hosts: linux 
  become: yes
  roles:
    - ansible-role-version-gather-linux

- hosts: localhost
  become: yes
  become_user: clacko
  post_tasks:
    - name: running ansible facts
#      shell: ansible linux -m setup -a "filter=ansible_local" 
      shell: echo "ansible linux -m setup | grep local_fact"

